# Generated by Django 2.2.3 on 2020-01-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actlog', '0002_auto_20200102_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='sched',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='section',
        ),
    ]
